language: node_js
node_js: node
branches:
  except:
  - master
script:
- npm install
- npm run firebase
- npm i firebase-tools
- firebase deploy --public="public" --project="dev-usecases" --token=$FIREBASE_TOKEN
