language: node_js
node_js: node
branches:
  except:
  - master
cache:
  yarn: true
  directories:
  - node_modules
install: npm i
script:
- npm run firebase
- npm i firebase-tools
- firebase deploy --public="public" --project="dev-usecases" --token=$FIREBASE_TOKEN
