language: node_js
node_js: 8
branches:
  except:
  - master
install: npm install
script:
- npm run firebase
- npm i firebase-tools
- firebase deploy --public="public" --project="dev-usecases" --token=$FIREBASE_TOKEN
